# Generated by Django 3.2.7 on 2021-10-12 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presc', '0002_auto_20211012_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='userID',
            new_name='user',
        ),
    ]
